#!/usr/bin/env python3
##
## EPITECH PROJECT, 2023
## 105 demo
## File description:
## 105 demo
##
import sys
from math import *


def print_h():
    print(
        "USAGE\n   ./105demography [code]+\n\nDESCRIPTION\n    code      country code"
    )
    return 0

def main(argv):
    if argv[0] == "-h":
        return print_h()
    return 0

if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except:
        sys.exit(84)
    sys.exit(0)